---
title: "Data Exploration"
author: "Monisha Eadlaa"
date: "4/19/2020"
output:
  word_document: default
  pdf_document: default
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Set your working directory
setwd("~/Eadala_Project_Environmental_Data_Analytics")
# Load your packages
library(tidyverse)
library(knitr)
# Set your ggplot theme
mytheme <- theme_light(base_size = 12) +
  theme(plot.background = element_rect(fill = "grey97"),
        panel.grid.major =element_line(linetype = "dotted"),
        panel.grid.minor = element_line(linetype = "dotted"), text=element_text(size = 14, 
color = "black", face = "bold"),
        axis.text = element_text(color = "grey40"), 
        legend.position = "right",
        legend.text = element_text(color = "grey40"))
theme_set(mytheme)

```

# Uploading the Nutrients and ChemistryPhysics raw data files associated with the NTL-LTER lakes datasets and formating the date column of each.

```{r}
# Load your datasets
Nutrients_raw <- read.csv("./Data/Raw/NTL-LTER_Lake_Nutrients_Raw.csv")
ChemistryPhysics_raw <- read.csv("./Data/Raw/NTL-LTER_Lake_ChemistryPhysics_Raw.csv")

head(Nutrients_raw)
Nutrients_raw$sampledate <- as.Date(Nutrients_raw$sampledate,
format = "%m/%d/%y")

head(ChemistryPhysics_raw)
ChemistryPhysics_raw$sampledate <- as.Date(ChemistryPhysics_raw$sampledate,
format = "%m/%d/%y")

```

# Data exploration of the Nutrients and ChemistryPhysics raw data files associated with the NTL-LTER lakes datasets

```{r}
dim(Nutrients_raw)
dim(ChemistryPhysics_raw)
str(Nutrients_raw)
str(ChemistryPhysics_raw)
colnames(Nutrients_raw)
colnames(ChemistryPhysics_raw)
summary(Nutrients_raw)
summary(ChemistryPhysics_raw)

```

## Plots


```{r, echo=FALSE}
TN.FreqPol.plot <- ggplot(Nutrients_raw) +
  geom_freqpoly(aes(x = tn_ug, color = lakename), bins = 50) +
  xlab("Total Nitrogen Concentration (µg/l)") + # To label the x axis
  ylab("Count") + # To label the y axis
  labs (color = "Lake Name") # To label the legend
print(TN.FreqPol.plot)

TN.Box.plot <- ggplot(Nutrients_raw) +
  geom_boxplot(aes(x = lakename, y = tn_ug, color = lakename)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  theme(legend.position="none") + # To removes the legend
  xlab("Lake Name") + # To label the x axis
  ylab("TN (µg/l)") # To label the y axis
print(TN.Box.plot)

TN.Scatter.plot <- ggplot(Nutrients_raw, aes(x = sampledate, y = tn_ug, color = lakename)) +
  geom_point() +
  stat_smooth(color = "black") +
  xlab("Lake Name") + # To label the x axis
  ylab("TN (µg/l)") + # To label the y axis
  labs (color = "Lake Name") # To label the legend
print(TN.Scatter.plot)

DO.Scatter.plot <- ggplot(ChemistryPhysics_raw, aes(x = sampledate, y = dissolvedOxygen, color = lakename)) +
  geom_point() +
  stat_smooth(color = "black") +
  ylim(0,25) + # To remove the outliers
  xlab("Lake Name") + # To label the x axis
  ylab("Dissolved Oxygen (mg/L)") + # To label the y axis
  labs (color = "Lake Name") # To label the legend
print(DO.Scatter.plot)
```

