---
title: "Processing/Wrangling"
author: "Monisha Eadala"
date: "4/14/2020"
output: pdf_document
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Set your working directory
setwd("~/Eadala_Project_Environmental_Data_Analytics")
# Load your packages
library(tidyverse)
library(knitr)
# Set your ggplot theme
mytheme <- theme_light(base_size = 12) +
  theme(plot.background = element_rect(fill = "grey97"),
        panel.grid.major =element_line(linetype = "dotted"),
        panel.grid.minor = element_line(linetype = "dotted"), text=element_text(size = 14, 
color = "black", face = "bold"),
        axis.text = element_text(color = "grey40"), 
        legend.position = "right",
        legend.text = element_text(color = "grey40"))
theme_set(mytheme)

```

# Data Wrangling

```{r}

list(unique(ChemistryPhysics_raw$year4))
list(unique(Nutrients_raw$year4))

Nutrients_processed <- Nutrients_raw %>%
  select(-lakeid, -depth_id, -nh34, -po4, -no23 ,-comments) %>%
  filter(year4 == 1991 | year4 == 1992 | year4 ==  1993 | year4 ==  1994 | year4 == 1999 | year4 ==  2000 | year4 == 2001 | year4 == 2002 | year4 == 2003 | year4 == 2005 | year4 ==  2006 | year4 == 2007| year4 == 2008 | year4 == 2009 | year4 == 2010 | year4 ==  2011 | year4 ==  2012 | year4 ==  2013 | year4 ==  2014 | year4 == 2015 | year4 == 2016)

list(unique(Nutrients_processed$lakename))

ChemistryPhysics_processed <- ChemistryPhysics_raw %>%
  select(-lakeid, -irradianceWater, -irradianceDeck, -comments) %>% 
  filter(year4 == 1991 | year4 == 1992 | year4 ==  1993 | year4 ==  1994 | year4 == 1999 | year4 ==  2000 | year4 == 2001 | year4 == 2002 | year4 == 2003 | year4 == 2005 | year4 ==  2006 | year4 == 2007| year4 == 2008 | year4 == 2009 | year4 == 2010 | year4 ==  2011 | year4 ==  2012 | year4 ==  2013 | year4 ==  2014 | year4 == 2015 | year4 == 2016)
list(unique(ChemistryPhysics_processed$lakename))

Combined_processed <- full_join(Nutrients_processed, ChemistryPhysics_processed) %>%
  filter(year4 == 1991 | year4 == 1992 | year4 ==  1993 | year4 ==  1994 | year4 == 1999 | year4 ==  2000 | year4 == 2001 | year4 == 2002 | year4 == 2003 | year4 == 2005 | year4 ==  2006 | year4 == 2007| year4 == 2008 | year4 == 2009 | year4 == 2010 | year4 ==  2011 | year4 ==  2012 | year4 ==  2013 | year4 ==  2014 | year4 == 2015 | year4 == 2016) %>%
  filter(lakename == "Paul Lake" | lakename == "Peter Lake" | lakename == "East Long Lake" | lakename == "West Long Lake" | lakename == "Tuesday Lake" | lakename == "Central Long Lake" | lakename == "Hummingbird Lake" | lakename == "Crampton Lake")
list(unique(Combined_processed$lakename))

write.csv(Combined_processed, row.names = FALSE, file = "./Data/Processed/Combined_processed.csv")

```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
